### ISSUE TITLE
Want to write this in pure Go

### ISSUE THREAD

**Issue by amaanq** [pg9182/tf2lzham#1]
This isn't really an issue, but I'm just reaching out because I want to write the LZHAM compression algorithm in pure Go and I am struggling a bit, so I was asking if you would be interested in working on this. You can check what I've done so far here (not a lot as of rn) https://github.com/amaanq/lzham-go

Cheers,
Amaan

**Comment by pg9182** [comment]
I don't currently have time to contribute, but I am definitely interested in the result if/when you finish this.
